trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  SolutionName: 'Demo App'
  EnvironmentUrl: 'https://org36750a0e.api.crm11.dynamics.com'
  PowerPlatformServiceConnection: 'Dev'
  GitHubServiceConnection: 'GitHubServiceConnection'
  BranchName: 'main'
  RepoName: 'testAutomation'
  OrgName: 'HD-IT-Development'

steps:
- task: PowerPlatformToolInstaller@2
  displayName: 'Install Power Platform Tools'

- script: |
    pac auth create --url "$(EnvironmentUrl)" --name "DevEnvironment"
    pac solution list --json > solutions.json
  displayName: 'Retrieve Available Solutions'
 
- script: |
    type solutions.json
  displayName: 'Show Available Solutions'
  
- task: PowerPlatformExportSolution@2
  displayName: 'Export Power Apps Solution'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: $(PowerPlatformServiceConnection)
    SolutionName: $(SolutionName)
    Environment: $(EnvironmentUrl)
    Managed: false
    AsyncOperation: true
    MaxAsyncWaitTime: 20

- task: PowerPlatformUnpackSolution@2
  displayName: 'Unpack Solution for Version Control'
  inputs:
    SolutionInputFile: '$(Build.SourcesDirectory)/$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)/$(SolutionName)-unpacked'
    SolutionType: 'Unmanaged'

- script: |
    git config --global user.email "guillermorodriguez-mon@hastingsdirect.com"
    git config --global user.name "EY Power Platform Source Control"
    git clone https://github.com/$(OrgName)/$(RepoName).git
    cd $(RepoName)
    git checkout $(BranchName)
    cp -r $(Build.SourcesDirectory)/$(SolutionName)-unpacked/* .
    git add .
    git commit -m "Exported solution $(SolutionName) on $(date)"
    git push origin $(BranchName)
  displayName: 'Commit & Push Solution to GitHub'
